name: "gitea"
aliases:
  - "git"
domain: "gitea.roadtotech.me"
description: "Self-Hosted Git Service & Code Repository"
visible: true
auth: false
networks:
  - proxy-net
env:
  SSH_DOMAIN: "gitea.roadtotech.me"
  SSH_PORT: "2223"
homepage:
  title: "Gitea"
  group: "Development & AI"
  icon: "gitea.png"
  container: "gitea"
  weight: 10
